"""
D&D 5e Core Data - Rules compliant character creation data.
Based on D&D 5th Edition Player's Handbook.
"""

RACES = {
    "human": {
        "name": "Człowiek",
        "name_en": "Human",
        "asi": {"str": 1, "dex": 1, "con": 1, "int": 1, "wis": 1, "cha": 1},
        "speed": 9,
        "size": "Średni",
        "traits": ["Wszechstronność: Dodatkowa biegłość w jednej umiejętności"],
        "languages": ["Wspólny", "+ 1 do wyboru"],
        "darkvision": False,
        "description": "Wszechstronna rasa ludzi, zdolna do wszystkiego.",
        "subraces": {},
    },
    "elf_high": {
        "name": "Elf Wysoki",
        "name_en": "High Elf",
        "asi": {"dex": 2, "int": 1},
        "speed": 9,
        "size": "Średni",
        "traits": [
            "Mroczne widzenie (18m)",
            "Odporność na zaklęcia: Przewaga na rzuty obronne Int, Mdr, Cha vs czary",
            "Elfie wykształcenie: Biegłość w postrzeganiu",
            "Trans (medytacja 4h zamiast snu 8h)",
            "Znajomość broni elfów",
            "1 sztuczka z listy czarownika (Int)",
        ],
        "languages": ["Wspólny", "Elficki", "+ 1 do wyboru"],
        "darkvision": True,
        "description": "Eleganckia i długowieczna rasa z afinią do magii.",
        "subraces": {},
    },
    "elf_wood": {
        "name": "Elf Leśny",
        "name_en": "Wood Elf",
        "asi": {"dex": 2, "wis": 1},
        "speed": 10.5,
        "size": "Średni",
        "traits": [
            "Mroczne widzenie (18m)",
            "Odporność na zaklęcia",
            "Elfie wykształcenie: Biegłość w postrzeganiu",
            "Trans",
            "Maska dziczy: Ukrycie w naturalnym środowisku",
            "Szybkość elfów leśnych: 10.5m",
        ],
        "languages": ["Wspólny", "Elficki"],
        "darkvision": True,
        "description": "Zwinna rasa elfów żyjących w harmonii z naturą.",
        "subraces": {},
    },
    "dwarf_hill": {
        "name": "Krasnolud Górski",
        "name_en": "Hill Dwarf",
        "asi": {"con": 2, "wis": 1},
        "speed": 7.5,
        "size": "Średni",
        "traits": [
            "Mroczne widzenie (18m)",
            "Odporność krasnoludów: Przewaga vs trucizny, odporność na trucizny",
            "Wyczucie kamienia: Biegłość w historii dot. kamienia, x2 premię za biegłość",
            "Waleczność: Biegłość w lekkiej zbroi, średniej zbroi, tarczach, bojowym toporem, ręcznym toporem, lekkim młotem, młotem bojowym",
            "Narzędzia: Biegłość w narzędziach kowala/stolarza/warzenia piwa",
            "Wytrwałość krasnoludów (3.6m ruchu bez zmniejszania prędkości przez ekwipunek)",
            "Wytrzymałość wzgórza: +1 max PW za poziom",
        ],
        "languages": ["Wspólny", "Krasnoludzki"],
        "darkvision": True,
        "description": "Odporni krasnoludy wzgórz, słynni z wytrzymałości i mądrości.",
        "subraces": {},
    },
    "dwarf_mountain": {
        "name": "Krasnolud Górski (Góry)",
        "name_en": "Mountain Dwarf",
        "asi": {"con": 2, "str": 2},
        "speed": 7.5,
        "size": "Średni",
        "traits": [
            "Mroczne widzenie (18m)",
            "Odporność krasnoludów",
            "Wyczucie kamienia",
            "Waleczność krasnoludów",
            "Narzędzia krasnoludzkie",
            "Wytrwałość krasnoludów",
            "Górska zbroja: Biegłość w ciężkiej zbroi",
        ],
        "languages": ["Wspólny", "Krasnoludzki"],
        "darkvision": True,
        "description": "Potężni krasnoludy gór, waleczni i silni.",
        "subraces": {},
    },
    "halfling_lightfoot": {
        "name": "Niziołek Zwinniec",
        "name_en": "Lightfoot Halfling",
        "asi": {"dex": 2, "cha": 1},
        "speed": 7.5,
        "size": "Mały",
        "traits": [
            "Szczęście: Ponów k20 jeśli wypadnie 1",
            "Nieustraszony: Przewaga vs strachu",
            "Zwinność niziołków: Możesz przejść przez pole stworzenia większego od ciebie",
            "Naturalne skrytość: Ukryj się za stworzeniem większym od ciebie",
        ],
        "languages": ["Wspólny", "Niziołkowy"],
        "darkvision": False,
        "description": "Mali i zwinni, niziołki zwinniki są mistrzami dyskrecji.",
        "subraces": {},
    },
    "halforc": {
        "name": "Pół-Ork",
        "name_en": "Half-Orc",
        "asi": {"str": 2, "con": 1},
        "speed": 9,
        "size": "Średni",
        "traits": [
            "Mroczne widzenie (18m)",
            "Groźny: Biegłość w zastraszaniu",
            "Brutalne ataki: +1k8 do trafień krytycznych bronią",
            "Nieustępliwość: 1x/długi odpoczynek, gdy spadniesz do 0 PW, możesz pozostać przy 1 PW",
        ],
        "languages": ["Wspólny", "Orczanski"],
        "darkvision": True,
        "description": "Silna i wytrzymała hybryda człowieka i orka.",
        "subraces": {},
    },
    "tiefling": {
        "name": "Tiefling",
        "name_en": "Tiefling",
        "asi": {"int": 1, "cha": 2},
        "speed": 9,
        "size": "Średni",
        "traits": [
            "Mroczne widzenie (18m)",
            "Piekielne dziedzictwo: Odporność na obrażenia od ognia",
            "Zaklęcia: Thaumaturgy (sztuczka), Hellish Rebuke (2lvl), Darkness (3lvl) - oparte na Charizmie",
        ],
        "languages": ["Wspólny", "Piekielny"],
        "darkvision": True,
        "description": "Istoty piekielnego pochodzenia o mrocznym uroku i magii.",
        "subraces": {},
    },
    "dragonborn": {
        "name": "Smoczorodny",
        "name_en": "Dragonborn",
        "asi": {"str": 2, "cha": 1},
        "speed": 9,
        "size": "Średni",
        "traits": [
            "Oddech smoka: Wybierz typ obrażeń, użyj jako ataku obszarowego (Con rzut obronny)",
            "Odporność na obrażenia: Typ zależny od rodowodu",
        ],
        "languages": ["Wspólny", "Smoczy"],
        "darkvision": False,
        "description": "Dumna rasa z smoczą krwią, zdolna do oddechu smoka.",
        "subraces": {},
    },
    "gnome_forest": {
        "name": "Gnom Leśny",
        "name_en": "Forest Gnome",
        "asi": {"int": 2, "dex": 1},
        "speed": 7.5,
        "size": "Mały",
        "traits": [
            "Mroczne widzenie (18m)",
            "Spryt gnoma: Przewaga na rzuty Int, Mdr, Cha vs magia",
            "Iluzja natury: Sztuczka Drobnych Złudzeń",
            "Rozmowa ze zwierzętami: Prosty komunikat z małymi naturalnymi zwierzętami",
        ],
        "languages": ["Wspólny", "Gnomskniy"],
        "darkvision": True,
        "description": "Żywiołowe i ciekawskie gnomy, zaprzyjaźnione z naturą.",
        "subraces": {},
    },
}

CLASSES = {
    "barbarian": {
        "name": "Barbarzyńca",
        "name_en": "Barbarian",
        "hit_die": 12,
        "primary_stats": ["str", "con"],
        "saving_throws": ["str", "con"],
        "armor_proficiencies": ["lekka", "średnia", "tarcze"],
        "weapon_proficiencies": ["prosta", "bojowa"],
        "num_skills": 2,
        "skill_choices": ["atletyka", "postrzeganie", "zastraszanie", "przetrwanie", "przyroda", "zwierzęta"],
        "features_1": [
            "Szał (Rage): Bonus do ataków i obrażeń od siły, odporność na obrażenia fizyczne. Użycia: 2",
            "Obrona bez pancerza: KP = 10 + modyfikator Zręczności + modyfikator Kondycji",
        ],
        "spellcasting": False,
        "description": "Dziki wojownik korzystający z prymitywnej siły i szału bojowego.",
        "subclasses": {
            "berserker": "Berserker - skupia się na szale i dodatkowych atakach",
            "totem_warrior": "Wojownik Totemu - mistyczna więź ze zwierzęciem totemicznym",
        },
        "primary_ability": "STR",
        "secondary_ability": "CON",
    },
    "bard": {
        "name": "Bard",
        "name_en": "Bard",
        "hit_die": 8,
        "primary_stats": ["cha"],
        "saving_throws": ["dex", "cha"],
        "armor_proficiencies": ["lekka"],
        "weapon_proficiencies": ["prosta", "rapier", "szpada", "krótki miecz"],
        "num_skills": 3,
        "skill_choices": "all",
        "features_1": [
            "Rzucanie zaklęć (Cha)",
            "Bardowska Inspiracja: Kostka inspiracji dla sojusznika (k6), użycia = mod Cha",
        ],
        "spellcasting": True,
        "spellcasting_stat": "cha",
        "description": "Magiczny pieśniarz czerpiący moc z muzyki i słów.",
        "subclasses": {
            "lore": "Kolegium Wiedzy - skupia się na magii i wiedzy",
            "valor": "Kolegium Waleczności - łączy magię z walką",
        },
        "primary_ability": "CHA",
    },
    "cleric": {
        "name": "Kleryk",
        "name_en": "Cleric",
        "hit_die": 8,
        "primary_stats": ["wis"],
        "saving_throws": ["wis", "cha"],
        "armor_proficiencies": ["lekka", "średnia", "tarcze"],
        "weapon_proficiencies": ["prosta"],
        "num_skills": 2,
        "skill_choices": ["historia", "medycyna", "perswazja", "religia", "wgląd"],
        "features_1": [
            "Rzucanie zaklęć (Mdr)",
            "Boska Domena: Wybierz domenę (Życia, Wiedzy, Światła, etc.)",
        ],
        "spellcasting": True,
        "spellcasting_stat": "wis",
        "description": "Kapłan boga, dysponujący boską magią i uzdrawianiem.",
        "subclasses": {
            "life": "Domena Życia - uzdrawianie i wsparcie",
            "light": "Domena Światła - ofensywna magia ognia",
        },
        "primary_ability": "WIS",
    },
    "druid": {
        "name": "Druid",
        "name_en": "Druid",
        "hit_die": 8,
        "primary_stats": ["wis"],
        "saving_throws": ["int", "wis"],
        "armor_proficiencies": ["lekka (niemagiczna)", "średnia (niemagiczna)", "tarcze (nie metalowe)"],
        "weapon_proficiencies": ["pałka", "sztylet", "dzida", "oszczep", "buława", "kij", "sierp", "proca"],
        "num_skills": 2,
        "skill_choices": ["arcana", "zwierzęta", "wgląd", "medycyna", "przyroda", "postrzeganie", "religia", "przetrwanie"],
        "features_1": [
            "Rzucanie zaklęć (Mdr)",
            "Druidzki język (druidic) - tajny język",
        ],
        "spellcasting": True,
        "spellcasting_stat": "wis",
        "description": "Strażnik natury władający magią przyrody i zdolny do przemiany.",
        "subclasses": {
            "land": "Krąg Ziemi - magia oparta na środowisku",
            "moon": "Krąg Księżyca - potężniejsza przemiana w zwierzę",
        },
        "primary_ability": "WIS",
    },
    "fighter": {
        "name": "Wojownik",
        "name_en": "Fighter",
        "hit_die": 10,
        "primary_stats": ["str", "dex"],
        "saving_throws": ["str", "con"],
        "armor_proficiencies": ["lekka", "średnia", "ciężka", "tarcze"],
        "weapon_proficiencies": ["prosta", "bojowa"],
        "num_skills": 2,
        "skill_choices": ["akrobatyka", "atletyka", "historia", "wgląd", "zastraszanie", "postrzeganie", "przetrwanie"],
        "features_1": [
            "Styl Walki: Wybierz specjalizację bojową",
            "Drugi Oddech: Ulecz 1k10 + poziom bojownika raz na krótki/długi odpoczynek",
        ],
        "spellcasting": False,
        "description": "Wszechstronny mistrz broni i technik walki.",
        "subclasses": {
            "champion": "Czempion - doskonałość fizyczna, krytyki na 19",
            "battlemaster": "Mistrz Bitewny - manewry taktyczne",
            "eldritch_knight": "Eldryczny Rycerz - wojownik z magią",
        },
        "primary_ability": "STR/DEX",
    },
    "monk": {
        "name": "Mnich",
        "name_en": "Monk",
        "hit_die": 8,
        "primary_stats": ["dex", "wis"],
        "saving_throws": ["str", "dex"],
        "armor_proficiencies": [],
        "weapon_proficiencies": ["prosta", "krótki miecz"],
        "num_skills": 2,
        "skill_choices": ["akrobatyka", "atletyka", "historia", "wgląd", "religia", "ukrycie"],
        "features_1": [
            "Nieuzbrojony: Obrona bez pancerza (10 + Zrc + Mdr)",
            "Ki: Pula punktów Ki = poziom",
            "Nieuzbrojony Atak: Bonus atak bez broni lub ki",
        ],
        "spellcasting": False,
        "description": "Ascetyczny wojownik doskonalący ciało i ducha poprzez medytację.",
        "primary_ability": "DEX/WIS",
    },
    "paladin": {
        "name": "Paladyn",
        "name_en": "Paladin",
        "hit_die": 10,
        "primary_stats": ["str", "cha"],
        "saving_throws": ["wis", "cha"],
        "armor_proficiencies": ["lekka", "średnia", "ciężka", "tarcze"],
        "weapon_proficiencies": ["prosta", "bojowa"],
        "num_skills": 2,
        "skill_choices": ["atletyka", "wgląd", "zastraszanie", "medycyna", "perswazja", "religia"],
        "features_1": [
            "Boskie Poczucie: Wykryj zło/dobro w promieniu 18m (Cha+1 razy/długi odpoczynek)",
            "Nałożenie Rąk: Lecz PW = poziom × 5 na długi odpoczynek",
        ],
        "spellcasting": True,
        "spellcasting_stat": "cha",
        "description": "Święty wojownik złączony przysięgą z boską mocą.",
        "primary_ability": "STR/CHA",
    },
    "ranger": {
        "name": "Łowca",
        "name_en": "Ranger",
        "hit_die": 10,
        "primary_stats": ["dex", "wis"],
        "saving_throws": ["str", "dex"],
        "armor_proficiencies": ["lekka", "średnia", "tarcze"],
        "weapon_proficiencies": ["prosta", "bojowa"],
        "num_skills": 3,
        "skill_choices": ["zwierzęta", "atletyka", "wgląd", "badanie", "przyroda", "postrzeganie", "ukrycie", "przetrwanie"],
        "features_1": [
            "Ulubiony Wróg: Wybierz typ wrogów, przewaga na śledzenie i wiedzę",
            "Naturalne Badanie: Wybierz typ terenu, ignorujesz trudny teren",
        ],
        "spellcasting": True,
        "spellcasting_stat": "wis",
        "description": "Strażnik dziczy, łowca i zwiadowca.",
        "primary_ability": "DEX/WIS",
    },
    "rogue": {
        "name": "Łotrzyk",
        "name_en": "Rogue",
        "hit_die": 8,
        "primary_stats": ["dex"],
        "saving_throws": ["dex", "int"],
        "armor_proficiencies": ["lekka"],
        "weapon_proficiencies": ["prosta", "ręczna kusza", "długi łuk", "rapier", "szpada", "krótki miecz"],
        "num_skills": 4,
        "skill_choices": ["akrobatyka", "atletyka", "oszustwo", "badanie", "wgląd", "zastraszanie", "badanie", "postrzeganie", "wykonanie", "perswazja", "sleight_of_hand", "ukrycie"],
        "features_1": [
            "Wiedza Eksperta: x2 premię za biegłość w 2 umiejętnościach",
            "Atak Skrytobójczy: +1k6 obrażeń gdy masz przewagę lub sojusznik jest obok celu",
            "Złodziejski żargon: Tajny język złodziei",
        ],
        "spellcasting": False,
        "description": "Skryty i zwinny mistrz sztuczek, infiltracji i nagłych ataków.",
        "primary_ability": "DEX",
    },
    "sorcerer": {
        "name": "Czarnoksiężnik",
        "name_en": "Sorcerer",
        "hit_die": 6,
        "primary_stats": ["cha"],
        "saving_throws": ["con", "cha"],
        "armor_proficiencies": [],
        "weapon_proficiencies": ["sztylet", "oszczep", "proca", "kij"],
        "num_skills": 2,
        "skill_choices": ["arcana", "oszustwo", "wgląd", "zastraszanie", "perswazja", "religia"],
        "features_1": [
            "Rzucanie zaklęć (Cha)",
            "Magiczne Źródło: Wybierz źródło mocy (Smocze, Dzikie)",
        ],
        "spellcasting": True,
        "spellcasting_stat": "cha",
        "description": "Mág czerpiący moc z wrodzonego daru magicznego.",
        "primary_ability": "CHA",
    },
    "warlock": {
        "name": "Mroczny Czarnoksiężnik",
        "name_en": "Warlock",
        "hit_die": 8,
        "primary_stats": ["cha"],
        "saving_throws": ["wis", "cha"],
        "armor_proficiencies": ["lekka"],
        "weapon_proficiencies": ["prosta"],
        "num_skills": 2,
        "skill_choices": ["arcana", "oszustwo", "historia", "zastraszanie", "badanie", "przyroda", "religia"],
        "features_1": [
            "Pakt Okultystyczny: Wybierz patrona (Archfey, Fiend, Great Old One)",
            "Magia Paktu: 1 miejsce zaklęcia, odnawialne po krótkim odpoczynku",
        ],
        "spellcasting": True,
        "spellcasting_stat": "cha",
        "description": "Czarnoksiężnik zawarty pakt z nadnaturalną istotą.",
        "primary_ability": "CHA",
    },
    "wizard": {
        "name": "Mag",
        "name_en": "Wizard",
        "hit_die": 6,
        "primary_stats": ["int"],
        "saving_throws": ["int", "wis"],
        "armor_proficiencies": [],
        "weapon_proficiencies": ["sztylet", "rzutka", "proca", "kij", "lekka kusza"],
        "num_skills": 2,
        "skill_choices": ["arcana", "historia", "wgląd", "badanie", "medycyna", "religia"],
        "features_1": [
            "Rzucanie zaclęć (Int)",
            "Księga zaklęć: Zawiera 6 zaklęć 1 poziomu",
            "Odzysk Arcanum: Odzyskaj miejsca zaklęć po krótkim odpoczynku",
        ],
        "spellcasting": True,
        "spellcasting_stat": "int",
        "description": "Uczony mag opanowujący arkana poprzez naukę i praktykę.",
        "primary_ability": "INT",
    },
}

BACKGROUNDS = {
    "acolyte": {
        "name": "Akolita",
        "skills": ["wgląd", "religia"],
        "tools": [],
        "languages": 2,
        "equipment": ["symbol święty", "modlitewnik", "5 kadzidełek", "szaty", "15 sz złota"],
        "feature": "Schronienie wiernych: Możesz liczyć na wsparcie świątyni",
        "description": "Spędziłeś życie w służbie świątynnej.",
    },
    "criminal": {
        "name": "Przestępca",
        "skills": ["oszustwo", "ukrycie"],
        "tools": ["narzędzia do gier", "narzędzia złodzieja"],
        "languages": 0,
        "equipment": ["łom", "ciemne ubranie z kapturem", "15 sz złota"],
        "feature": "Kontakt w podziemiu: Masz kontakt który może pomyć w kryminalnych sprawach",
        "description": "Prowadziłeś życie na skraju prawa.",
    },
    "folk_hero": {
        "name": "Bohater Ludu",
        "skills": ["obsługa zwierząt", "przetrwanie"],
        "tools": ["narzędzia rzemieślnicze", "pojazdy lądowe"],
        "languages": 0,
        "equipment": ["narzędzia rzemieślnicze", "łopata", "żelazny garnek", "ubranie wieśniaka", "10 sz złota"],
        "feature": "Schronienie ludu: Zwykli ludzie cię wspierają i ukryją",
        "description": "Wywodzisz się ze zwykłego ludu i bronisz ich spraw.",
    },
    "noble": {
        "name": "Szlachcic",
        "skills": ["historia", "perswazja"],
        "tools": ["narzędzia do gier"],
        "languages": 1,
        "equipment": ["dobre ubrania", "pierścień z sygnetu", "dokument szlachectwa", "25 sz złota"],
        "feature": "Przywilej pozycji: Twoja pozycja otwiera wiele drzwi",
        "description": "Urodzony w zamożnej i wpływowej rodzinie.",
    },
    "sage": {
        "name": "Uczony",
        "skills": ["arcana", "historia"],
        "tools": [],
        "languages": 2,
        "equipment": ["butelka atramentu", "pióro", "nóż do listów", "10 arkuszy pergaminu", "10 sz złota"],
        "feature": "Badacz: Wiesz gdzie szukać informacji gdy ich nie znasz",
        "description": "Poświęciłeś życie zdobywaniu wiedzy.",
    },
    "soldier": {
        "name": "Żołnierz",
        "skills": ["atletyka", "zastraszanie"],
        "tools": ["narzędzia do gier", "pojazdy lądowe"],
        "languages": 0,
        "equipment": ["insygnia rangi", "trofea z bitew", "kości do gry", "zwykłe ubrania", "10 sz złota"],
        "feature": "Stopień wojskowy: Żołnierze rozpoznają twój autorytet",
        "description": "Służyłeś w armii i przeżyłeś bitwy.",
    },
    "outlander": {
        "name": "Wędrowiec",
        "skills": ["atletyka", "przetrwanie"],
        "tools": ["instrument muzyczny"],
        "languages": 1,
        "equipment": ["kij", "pułapka na myśliwce", "trofea z polowania", "ubrania podróżne", "10 sz złota"],
        "feature": "Wędrownik: Doskonale znasz dzikie tereny i potrafisz znaleźć żywność",
        "description": "Wychowałeś się poza cywilizacją, w dzikich terenach.",
    },
    "entertainer": {
        "name": "Artysta",
        "skills": ["akrobatyka", "wykonanie"],
        "tools": ["instrument muzyczny", "zestaw przebrań"],
        "languages": 0,
        "equipment": ["instrument muzyczny", "przychylność fana", "kostium", "15 sz złota"],
        "feature": "Przez noc sławny: Możesz zawsze liczyć na nocleg w miejscu gdzie grałeś",
        "description": "Rozkwitałeś na scenie i żyłeś dla oklasków.",
    },
    "hermit": {
        "name": "Pustelnik",
        "skills": ["medycyna", "religia"],
        "tools": ["zestaw ziołowy"],
        "languages": 1,
        "equipment": ["etui do pergaminu", "koc zimowy", "zestaw ziołowy", "5 sz złota"],
        "feature": "Odkrycie: Odosobnienie dało ci unikalną wiedzę lub sekret",
        "description": "Żyłeś w odosobnieniu przez długi czas.",
    },
    "guild_artisan": {
        "name": "Rzemieślnik",
        "skills": ["wgląd", "perswazja"],
        "tools": ["narzędzia rzemieślnicze"],
        "languages": 1,
        "equipment": ["narzędzia rzemieślnicze", "list polecający od gildii", "ubrania podróżne", "15 sz złota"],
        "feature": "Przynależność do gildii: Gildia zapewni ci nocleg i pomoc",
        "description": "Jesteś mistrzem rzemiosła i członkiem gildii.",
    },
}

SKILLS = {
    "akrobatyka": {"stat": "dex", "name": "Akrobatyka"},
    "zwierzęta": {"stat": "wis", "name": "Opieka nad zwierzętami"},
    "arcana": {"stat": "int", "name": "Wiedza tajemna"},
    "atletyka": {"stat": "str", "name": "Atletyka"},
    "oszustwo": {"stat": "cha", "name": "Oszustwo"},
    "historia": {"stat": "int", "name": "Historia"},
    "wgląd": {"stat": "wis", "name": "Intuicja"},
    "zastraszanie": {"stat": "cha", "name": "Zastraszanie"},
    "badanie": {"stat": "int", "name": "Badanie"},
    "medycyna": {"stat": "wis", "name": "Medycyna"},
    "przyroda": {"stat": "int", "name": "Przyroda"},
    "postrzeganie": {"stat": "wis", "name": "Percepcja"},
    "wykonanie": {"stat": "cha", "name": "Występy"},
    "perswazja": {"stat": "cha", "name": "Perswazja"},
    "religia": {"stat": "int", "name": "Religia"},
    "sleight_of_hand": {"name": "Zwinne dłonie", "name_en": "Sleight of Hand", "stat": "dex", "desc": "Sztuczki manualne, kradzież kieszonkowa."},
    "stealth": {"name": "Ukrycie", "name_en": "Stealth", "stat": "dex", "desc": "Bezszelestne poruszanie się, chowanie w cieniu."},
    "survival": {"name": "Sztuka przetrwania", "name_en": "Survival", "stat": "wis", "desc": "Tropienie, orientacja w terenie, polowanie."}
}

SPELLS = {
    "cantrip": [
        {"id": "acid_splash", "name_pl": "Rozprysk Kwasu", "name_en": "Acid Splash", "classes": ["sorcerer", "wizard"]},
        {"id": "chill_touch", "name_pl": "Trupi Dotyk", "name_en": "Chill Touch", "classes": ["sorcerer", "warlock", "wizard"]},
        {"id": "dancing_lights", "name_pl": "Tańczące Światła", "name_en": "Dancing Lights", "classes": ["bard", "sorcerer", "wizard"]},
        {"id": "eldritch_blast", "name_pl": "Niesamowite Uderzenie", "name_en": "Eldritch Blast", "classes": ["warlock"]},
        {"id": "fire_bolt", "name_pl": "Ognisty Pocisk", "name_en": "Fire Bolt", "classes": ["sorcerer", "wizard"]},
        {"id": "guidance", "name_pl": "Przewodnictwo", "name_en": "Guidance", "classes": ["cleric", "druid"]},
        {"id": "light", "name_pl": "Światło", "name_en": "Light", "classes": ["bard", "cleric", "sorcerer", "wizard"]},
        {"id": "mage_hand", "name_pl": "Magiczna Dłoń", "name_en": "Mage Hand", "classes": ["bard", "sorcerer", "warlock", "wizard"]},
        {"id": "minor_illusion", "name_pl": "Drobna Iluzja", "name_en": "Minor Illusion", "classes": ["bard", "sorcerer", "warlock", "wizard"]},
        {"id": "prestidigitation", "name_pl": "Sztuczka", "name_en": "Prestidigitation", "classes": ["bard", "sorcerer", "warlock", "wizard"]},
        {"id": "ray_of_frost", "name_pl": "Promień Mrozu", "name_en": "Ray of Frost", "classes": ["sorcerer", "wizard"]},
        {"id": "sacred_flame", "name_pl": "Święty Płomień", "name_en": "Sacred Flame", "classes": ["cleric"]},
        {"id": "shillelagh", "name_pl": "Kij", "name_en": "Shillelagh", "classes": ["druid"]},
        {"id": "shocking_grasp", "name_pl": "Porażający Uścisk", "name_en": "Shocking Grasp", "classes": ["sorcerer", "wizard"]},
        {"id": "thaumaturgy", "name_pl": "Taumaturgia", "name_en": "Thaumaturgy", "classes": ["cleric"]},
        {"id": "vicious_mockery", "name_pl": "Okrutna Drwina", "name_en": "Vicious Mockery", "classes": ["bard"]}
    ],
    "level_1": [
        {"id": "alarm", "name_pl": "Alarm", "name_en": "Alarm", "classes": ["ranger", "wizard"]},
        {"id": "animal_friendship", "name_pl": "Przyjaźń Zwierząt", "name_en": "Animal Friendship", "classes": ["bard", "druid", "ranger"]},
        {"id": "bane", "name_pl": "Zguba", "name_en": "Bane", "classes": ["bard", "cleric"]},
        {"id": "bless", "name_pl": "Błogosławieństwo", "name_en": "Bless", "classes": ["cleric", "paladin"]},
        {"id": "burning_hands", "name_pl": "Płonące Dłonie", "name_en": "Burning Hands", "classes": ["sorcerer", "wizard"]},
        {"id": "charm_person", "name_pl": "Zauroczenie Osoby", "name_en": "Charm Person", "classes": ["bard", "druid", "sorcerer", "warlock", "wizard"]},
        {"id": "color_spray", "name_pl": "Barwne Kaskady", "name_en": "Color Spray", "classes": ["sorcerer", "wizard"]},
        {"id": "command", "name_pl": "Rozkaz", "name_en": "Command", "classes": ["cleric", "paladin"]},
        {"id": "comprehend_languages", "name_pl": "Zrozumienie Języków", "name_en": "Comprehend Languages", "classes": ["bard", "sorcerer", "warlock", "wizard"]},
        {"id": "cure_wounds", "name_pl": "Leczenie Ran", "name_en": "Cure Wounds", "classes": ["bard", "cleric", "druid", "paladin", "ranger"]},
        {"id": "detect_magic", "name_pl": "Wykrycie Magii", "name_en": "Detect Magic", "classes": ["bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "wizard"]},
        {"id": "disguise_self", "name_pl": "Zmiana Wyglądu", "name_en": "Disguise Self", "classes": ["bard", "sorcerer", "wizard"]},
        {"id": "entangle", "name_pl": "Oplątanie", "name_en": "Entangle", "classes": ["druid"]},
        {"id": "faerie_fire", "name_pl": "Ogień Faerie", "name_en": "Faerie Fire", "classes": ["bard", "druid"]},
        {"id": "feather_fall", "name_pl": "Piórkowe Opadanie", "name_en": "Feather Fall", "classes": ["bard", "sorcerer", "wizard"]},
        {"id": "find_familiar", "name_pl": "Znalezienie Chowańca", "name_en": "Find Familiar", "classes": ["wizard"]},
        {"id": "guiding_bolt", "name_pl": "Naprowadzający Pocisk", "name_en": "Guiding Bolt", "classes": ["cleric"]},
        {"id": "healing_word", "name_pl": "Lecznicze Słowo", "name_en": "Healing Word", "classes": ["bard", "cleric", "druid"]},
        {"id": "hellish_rebuke", "name_pl": "Piekielna Reprymenda", "name_en": "Hellish Rebuke", "classes": ["warlock"]},
        {"id": "heroism", "name_pl": "Heroizm", "name_en": "Heroism", "classes": ["bard", "paladin"]},
        {"id": "hex", "name_pl": "Klątwa", "name_en": "Hex", "classes": ["warlock"]},
        {"id": "identify", "name_pl": "Identyfikacja", "name_en": "Identify", "classes": ["bard", "wizard"]},
        {"id": "inflict_wounds", "name_pl": "Zadawanie Ran", "name_en": "Inflict Wounds", "classes": ["cleric"]},
        {"id": "mage_armor", "name_pl": "Zbroja Maga", "name_en": "Mage Armor", "classes": ["sorcerer", "wizard"]},
        {"id": "magic_missile", "name_pl": "Magiczny Pocisk", "name_en": "Magic Missile", "classes": ["sorcerer", "wizard"]},
        {"id": "sanctuary", "name_pl": "Sanktuarium", "name_en": "Sanctuary", "classes": ["cleric"]},
        {"id": "shield", "name_pl": "Tarcza", "name_en": "Shield", "classes": ["sorcerer", "wizard"]},
        {"id": "sleep", "name_pl": "Uśpienie", "name_en": "Sleep", "classes": ["bard", "sorcerer", "wizard"]},
        {"id": "thunderwave", "name_pl": "Fala Gromu", "name_en": "Thunderwave", "classes": ["bard", "druid", "sorcerer", "wizard"]}
    ]
}

STAT_NAMES = {
    "str": "Siła",
    "dex": "Zręczność",
    "con": "Kondycja",
    "int": "Inteligencja",
    "wis": "Mądrość",
    "cha": "Charyzma",
}

# Standard Array option (D&D 5e)
STANDARD_ARRAY = [15, 14, 13, 12, 10, 8]

# Point Buy costs (D&D 5e)
POINT_BUY_COSTS = {8: 0, 9: 1, 10: 2, 11: 3, 12: 4, 13: 5, 14: 7, 15: 9}
POINT_BUY_TOTAL = 27
POINT_BUY_MIN = 8
POINT_BUY_MAX = 15

# Proficiency bonus by level
PROFICIENCY_BY_LEVEL = {
    1: 2, 2: 2, 3: 2, 4: 2,
    5: 3, 6: 3, 7: 3, 8: 3,
    9: 4, 10: 4, 11: 4, 12: 4,
    13: 5, 14: 5, 15: 5, 16: 5,
    17: 6, 18: 6, 19: 6, 20: 6,
}

# Optimal stat priorities for auto-assign
CLASS_STAT_PRIORITY = {
    "barbarian": ["str", "con", "dex", "wis", "int", "cha"],
    "bard": ["cha", "dex", "con", "int", "wis", "str"],
    "cleric": ["wis", "con", "str", "cha", "dex", "int"],
    "druid": ["wis", "con", "int", "dex", "str", "cha"],
    "fighter": ["str", "con", "dex", "wis", "cha", "int"],
    "monk": ["dex", "wis", "con", "str", "int", "cha"],
    "paladin": ["str", "cha", "con", "wis", "dex", "int"],
    "ranger": ["dex", "wis", "con", "str", "int", "cha"],
    "rogue": ["dex", "int", "con", "cha", "wis", "str"],
    "sorcerer": ["cha", "con", "dex", "int", "wis", "str"],
    "warlock": ["cha", "con", "dex", "wis", "int", "str"],
    "wizard": ["int", "con", "dex", "wis", "cha", "str"],
}